[@GOOGLE]
ALL : device/google/malibu/sepolicy/certificates/certs/app.x509.pem

[@CAMERASERVICES]
ALL : device/google/malibu/sepolicy/certificates/certs/com_google_android_apps_camera_services.x509.pem

[@PMS]
ALL : device/google/malibu/sepolicy/certificates/certs/com_google_android_modem_pms.x509.pem

[@EUICCSUPPORTPIXEL]
ALL : device/google/malibu/sepolicy/certificates/certs/EuiccSupportPixel.x509.pem
